name: CI

on:
  push:
    branches:
      - main

permissions:
  contents: write
  packages: write

jobs:
  upload-blossom-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Upload to Blossom
        uses: Origami74/upload-blossom-action@main
        with:
          host: 'https://blossom.swissdash.site/'
          filePath: 'main.ts'
