name: CI

on:
  push:
    branches:
      - main

permissions:
  contents: write
  packages: write

jobs:
  build-and-package:
    runs-on: ubuntu-latest
    steps:
      - name: Upload to Blossom
        uses: Origami74/upload-blossom-action@main